services:
  - type: web
    name: healthyou
    env: python
    buildCommand: 
      - pip install -r requirements.txt
      - python migrate.py
    startCommand: |
      gunicorn -w 4 -b 0.0.0.0:8000 app:app